# Generated by Django 5.0.6 on 2024-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_camera_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
