# Generated by Django 5.0.6 on 2024-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('specific_location', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('compression_format', models.CharField(max_length=100)),
                ('network_stream_protocol', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
