# Generated by Django 5.0.6 on 2024-05-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='mac_address',
            new_name='ip_address',
        ),
    ]
