# Generated by Django 5.0.6 on 2024-05-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_rename_mac_address_camera_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='compression_format',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='is_enabled',
        ),
    ]
